import { HexagramMetadata } from '@/types/metadata';

/**
 * 六爻卦 (Hexagram) Metadata
 * Key 順序：[初, 二, 三, 四, 五, 上]
 */
export const HEXAGRAM_DATA: Record<string, HexagramMetadata> = {
  '111111': {
    name: '乾',
    index: 1,
    judgment: '元，亨，利，貞。',
    monograms: [
      { statement: '初九：潛龍勿用。', meaning: '龍尚潛伏，時機未到，宜收斂守靜。' },
      { statement: '九二：見龍在田，利見大人。', meaning: '才華初露，有利於尋求貴人指引。' },
      {
        statement: '九三：君子終日乾乾，夕惕若，厲無咎。',
        meaning: '勤奮不懈，時刻警惕，雖有危險但無災難。',
      },
      { statement: '九四：或躍在淵，無咎。', meaning: '處於進退關鍵期，根據時機靈活應變。' },
      {
        statement: '九五：飛龍在天，利見大人。',
        meaning: '大展鴻圖，正如日中天，是成就事業的最佳時機。',
      },
      { statement: '上九：亢龍有悔。', meaning: '物極必反，警惕盈不可久，應知進退。' },
    ],
  },
  '000000': {
    name: '坤',
    index: 2,
    judgment: '元，亨，利牝馬之貞。君子有攸往，先迷後得主利。西南得朋，東北喪朋，安貞吉。',
    monograms: [
      { statement: '初六：履霜，堅冰至。', meaning: '看見微小的徵兆，就應預見到後續的嚴峻趨勢。' },
      {
        statement: '六二：直、方、大，不習無不利。',
        meaning: '正直、方正、寬大，順應自然不需人為雕琢。',
      },
      {
        statement: '六三：含章可貞，或從王事，無成有終。',
        meaning: '內斂才華，盡職盡責而不居功。',
      },
      {
        statement: '六四：括囊，無咎，無譽。',
        meaning: '謹言慎行，像紮緊袋口一樣，雖無稱譽但也無災禍。',
      },
      { statement: '六五：黃裳，元吉。', meaning: '處事得中，內德外顯，是大吉之兆。' },
      { statement: '上六：龍戰於野，其血玄黃。', meaning: '陰陽相爭到極點，兩敗俱傷。' },
    ],
  },
  '100010': {
    name: '屯',
    index: 3,
    judgment: '元亨，利貞。勿用有攸往，利建侯。',
    monograms: [
      { statement: '初九：磐桓，利居貞，利建侯。', meaning: '' },
      { statement: '六二：屯如邅如，乘馬班如。匪寇婚媾，女子貞不字，十年乃字。', meaning: '' },
      { statement: '六三：即鹿無虞，惟入于林中。君子幾不如舍，往吝。', meaning: '。' },
      { statement: '六四：乘馬班如，求婚媾。往吉，無不利。', meaning: '' },
      { statement: '九五：屯其膏，小貞吉，大貞凶。', meaning: '' },
      { statement: '上六：乘馬班如，泣血漣如。', meaning: '' },
    ],
  },
  '010001': {
    name: '蒙',
    index: 4,
    judgment: '亨。匪我求童蒙，童蒙求我。初筮告，再三瀆，瀆則不告，利貞。',
    monograms: [
      { statement: '初六：發蒙。利用刑人，用說桎梏，以往吝。', meaning: '' },
      { statement: '九二：包蒙，吉。納婦吉，子克家。', meaning: '' },
      { statement: '六三：勿用取女，見金夫，不有躬，無攸利。', meaning: '。' },
      { statement: '六四：困蒙，吝。', meaning: '' },
      { statement: '九五：童蒙，吉。', meaning: '' },
      { statement: '上九：擊蒙，不利為寇，利禦寇。', meaning: '' },
    ],
  },
  '111010': {
    name: '需',
    index: 5,
    judgment: '有孚，光亨，貞吉，利涉大川。',
    monograms: [
      { statement: '初九：需于郊，利用恆，無咎。', meaning: '' },
      { statement: '九二：需于沙，小有言，終吉。', meaning: '' },
      { statement: '九三：需于泥，致寇至。', meaning: '。' },
      { statement: '六四：需于血，出自穴。', meaning: '' },
      { statement: '九五：需于酒食，貞吉。', meaning: '' },
      { statement: '上九：入于穴，有不速之客三人來。敬之，終吉。', meaning: '' },
    ],
  },
  '010111': {
    name: '訟',
    index: 6,
    judgment: '有孚，窒惕，中吉，終凶。利見大人，不利涉大川。',
    monograms: [
      { statement: '初六：不永所事，小有言，終吉。', meaning: '' },
      { statement: '九二：不克訟，歸而逋其邑，人三百戶，無眚。', meaning: '' },
      { statement: '六三：食舊德，貞厲，終吉。或從王事，無成。', meaning: '。' },
      { statement: '九四：不克訟，復即命渝，安貞吉。', meaning: '' },
      { statement: '九五：訟，元吉。', meaning: '' },
      { statement: '上九：或錫之鞶帶，終朝三褫之。', meaning: '' },
    ],
  },
  '010000': {
    name: '師',
    index: 7,
    judgment: '貞，丈人吉，無咎。',
    monograms: [
      { statement: '初六：師出以律，否臧凶。', meaning: '' },
      { statement: '九二：在師中吉，無咎，王三錫命。', meaning: '' },
      { statement: '六三：師或輿尸，凶。', meaning: '。' },
      { statement: '六四：師左次，無咎。', meaning: '' },
      { statement: '六五：田有禽，利執言，無咎。長子帥師，弟子輿尸，貞凶。', meaning: '' },
      { statement: '上六：大君有命，開國承家，小人勿用。', meaning: '' },
    ],
  },
  '000010': {
    name: '比',
    index: 8,
    judgment: '吉。原筮元永貞，無咎。不寧方來，後夫凶。',
    monograms: [
      { statement: '初六：有孚比之，無咎。有孚盈缶，終來有它吉。', meaning: '' },
      { statement: '六二：比之自內，貞吉。', meaning: '' },
      { statement: '六三：比之匪人。', meaning: '。' },
      { statement: '六四：外比之，貞吉。', meaning: '' },
      { statement: '九五：顯比，王用三驅，失前禽。邑人不誡，吉。', meaning: '' },
      { statement: '上六：比之無首，凶。', meaning: '' },
    ],
  },
  '111011': {
    name: '小畜',
    index: 9,
    judgment: '亨。密雲不雨，自我西郊。',
    monograms: [
      { statement: '初九：復自道，何其咎？吉。', meaning: '' },
      { statement: '九二：牽復，吉。', meaning: '' },
      { statement: '九三：輿說輻，夫妻反目。', meaning: '。' },
      { statement: '六四：有孚，血去惕出，無咎。', meaning: '' },
      { statement: '九五：有孚攣如，富以其鄰。', meaning: '' },
      { statement: '上九：既雨既處，尚德載，婦貞厲。月幾望，君子征凶。', meaning: '' },
    ],
  },
  '110111': {
    name: '履',
    index: 10,
    judgment: '虎尾，不咥人，亨。',
    monograms: [
      { statement: '初九：素履，往，無咎。', meaning: '' },
      { statement: '九二：履道坦坦，幽人貞吉。', meaning: '' },
      { statement: '六三：眇能視，跛能履。履虎尾，咥人，凶。武人為于大君。', meaning: '。' },
      { statement: '九四：履虎尾，愬愬，終吉。', meaning: '' },
      { statement: '九五：夬履，貞厲。', meaning: '' },
      { statement: '上九：視履，考祥其旋，元吉。', meaning: '' },
    ],
  },
  '111000': {
    name: '泰',
    index: 11,
    judgment: '小往大來，吉亨。',
    monograms: [
      {
        statement: '初九：拔茅茹，以其彙，征吉。',
        meaning: '志同道合者互相引薦，共同進取是大吉。',
      },
      {
        statement: '九二：包荒，用馮河，不暇遺...',
        meaning: '心懷包容，剛毅果斷，不遺棄疏遠之人。',
      },
      {
        statement: '九三：無平不陂，無往不復，艱貞無咎。',
        meaning: '天道循環，處安思危，艱難時刻保持正道。',
      },
      {
        statement: '六四：翩翩不富，以其鄰，不戒以信。',
        meaning: '誠信相待，與志同道合者不約而同。',
      },
      { statement: '六五：帝乙歸妹，以祉元吉。', meaning: '放下尊貴身分與人和諧，獲得福澤。' },
      { statement: '上六：城復於隍，勿用師。', meaning: '大勢已去，不宜訴諸武力，應守靜以對。' },
    ],
  },
  '000111': {
    name: '否',
    index: 12,
    judgment: '否之匪人，不利君子貞。',
    monograms: [
      { statement: '初六：拔茅茹，以其彙，貞吉亨。', meaning: '局勢不利時，與同道之人退守自保。' },
      { statement: '六二：包承，小人吉，大人否亨。', meaning: '小人趨炎附勢，君子應守住清高。' },
      { statement: '六三：包羞。', meaning: '心中隱藏著羞愧之事。' },
      { statement: '九四：有命無咎，疇離祉。', meaning: '順應天命，同類之人也能獲得福澤。' },
      { statement: '九五：休否，大人吉。', meaning: '終止混亂局勢，有德之人獲得吉祥。' },
      { statement: '上九：傾否，先否後喜。', meaning: '阻塞的局面傾覆，局勢由壞轉好。' },
    ],
  },
  '101111': {
    name: '同人',
    index: 13,
    judgment: '同人于野，亨。利涉大川，利君子貞。',
    monograms: [
      { statement: '初九：同人于門，無咎。', meaning: '' },
      { statement: '六二：同人于宗，吝。', meaning: '' },
      { statement: '九三：伏戎于莽，升其高陵，三歲不興。', meaning: '。' },
      { statement: '九四：乘其墉，弗克攻，吉。', meaning: '' },
      { statement: '九五：同人，先號咷而後笑，大師克相遇。', meaning: '' },
      { statement: '上九：同人于郊，無悔。', meaning: '' },
    ],
  },
  '111101': {
    name: '大有',
    index: 14,
    judgment: '大有，元亨。',
    monograms: [
      { statement: '初九：無交害，匪咎，艱則無咎。', meaning: '' },
      { statement: '九二：大車以載，有攸往，無咎。', meaning: '' },
      { statement: '九三：公用亨于天子，小人弗克。', meaning: '。' },
      { statement: '九四：匪其彭，無咎。', meaning: '' },
      { statement: '六五：厥孚交如，威如，吉。', meaning: '' },
      { statement: '上九：自天祐之，吉，無不利。', meaning: '' },
    ],
  },
  '001000': {
    name: '謙',
    index: 15,
    judgment: '亨，君子有終。',
    monograms: [
      { statement: '初六：謙謙君子，用涉大川，吉。', meaning: '' },
      { statement: '六二：鳴謙，貞吉。', meaning: '' },
      { statement: '九三：勞謙，君子有終，吉。', meaning: '。' },
      { statement: '六四：無不利，撝謙。', meaning: '' },
      { statement: '六五：不富以其鄰，利用侵伐，無不利。', meaning: '' },
      { statement: '上六：鳴謙，利用行師，征邑國。', meaning: '' },
    ],
  },
  '000100': {
    name: '豫',
    index: 16,
    judgment: '利建侯、行師。',
    monograms: [
      { statement: '初六：鳴豫，凶。', meaning: '' },
      { statement: '六二：介于石，不終日，貞吉。', meaning: '' },
      { statement: '六三：盱豫，悔，遲有悔。', meaning: '。' },
      { statement: '九四：由豫，大有得。勿疑，朋盍簪。', meaning: '' },
      { statement: '六五：貞疾，恆不死。', meaning: '' },
      { statement: '上六：冥豫，成有渝，無咎。', meaning: '' },
    ],
  },
  '100110': {
    name: '隨',
    index: 17,
    judgment: '元亨利貞，無咎。',
    monograms: [
      { statement: '初九：官有渝，貞吉。出門交有功。', meaning: '' },
      { statement: '六二：係小子，失丈夫。', meaning: '' },
      { statement: '六三：係丈夫，失小子。隨有求得，利居貞。', meaning: '。' },
      { statement: '九四：隨有獲，貞凶。有孚在道以明，何咎？', meaning: '' },
      { statement: '九五：孚于嘉，吉。', meaning: '' },
      { statement: '上六：拘係之，乃從維之，王用亨于西山。', meaning: '' },
    ],
  },
  '011001': {
    name: '蠱',
    index: 18,
    judgment: '元亨，利涉大川。先甲三日，後甲三日。',
    monograms: [
      { statement: '初六：幹父之蠱。有子，考無咎，厲，終吉。', meaning: '' },
      { statement: '九二：幹母之蠱，不可貞。', meaning: '' },
      { statement: '九三：幹父之蠱，小有悔，無大咎。', meaning: '。' },
      { statement: '六四：裕父之蠱，往見吝。', meaning: '' },
      { statement: '六五：幹父之蠱，用譽。', meaning: '' },
      { statement: '上九：不事王侯，高尚其事。', meaning: '' },
    ],
  },
  '110000': {
    name: '臨',
    index: 19,
    judgment: '元亨利貞，至于八月有凶。',
    monograms: [
      { statement: '初九：咸臨，貞吉。', meaning: '' },
      { statement: '九二：咸臨，吉，無不利。', meaning: '' },
      { statement: '六三：甘臨，無攸利，既憂之，無咎。', meaning: '。' },
      { statement: '六四：至臨，無咎。', meaning: '' },
      { statement: '六五：知臨，大君之宜，吉。', meaning: '' },
      { statement: '上六：敦臨，吉，無咎。', meaning: '' },
    ],
  },
  '000011': {
    name: '觀',
    index: 20,
    judgment: '盥而不薦，有孚顒若。',
    monograms: [
      { statement: '初六：童觀，小人無咎，君子吝。', meaning: '' },
      { statement: '六二：闚觀，利女貞。', meaning: '' },
      { statement: '六三：觀我生，進退。', meaning: '。' },
      { statement: '六四：觀國之光，利用賓于王。', meaning: '' },
      { statement: '九五：觀我生，君子無咎。', meaning: '' },
      { statement: '上九：觀其生，君子無咎。', meaning: '' },
    ],
  },
  '100101': {
    name: '噬嗑',
    index: 21,
    judgment: '亨，利用獄。',
    monograms: [
      { statement: '初九：屨校滅趾，無咎。', meaning: '' },
      { statement: '六二：噬膚滅鼻，無咎。', meaning: '' },
      { statement: '六三：噬腊肉，遇毒。小吝，無咎。', meaning: '。' },
      { statement: '九四：噬乾胏，得金矢。利艱貞，吉。', meaning: '' },
      { statement: '六五：噬乾肉，得黃金。貞厲，無咎。', meaning: '' },
      { statement: '上九：何校滅耳，凶。', meaning: '' },
    ],
  },
  '101001': {
    name: '賁',
    index: 22,
    judgment: '亨，小利有攸往。',
    monograms: [
      { statement: '初九：賁其趾，舍車而徒。', meaning: '' },
      { statement: '六二：賁其須。', meaning: '' },
      { statement: '六三：賁如濡如，永貞吉。', meaning: '。' },
      { statement: '六四：賁如皤如，白馬翰如，匪寇婚媾。', meaning: '' },
      { statement: '六五：賁于丘園，束帛戔戔。吝，終吉。', meaning: '' },
      { statement: '上九：白賁，無咎。', meaning: '' },
    ],
  },
  '000001': {
    name: '剝',
    index: 23,
    judgment: '不利有攸往。',
    monograms: [
      { statement: '初六：剝牀以足，蔑貞凶。', meaning: '' },
      { statement: '六二：剝牀以辨，蔑貞凶。', meaning: '' },
      { statement: '六三：剝之無咎。', meaning: '。' },
      { statement: '六四：剝牀以膚，凶。', meaning: '' },
      { statement: '六五：貫魚，以宮人寵，無不利。', meaning: '' },
      { statement: '上九：碩果不食，君子得輿，小人剝廬。', meaning: '' },
    ],
  },
  '100000': {
    name: '復',
    index: 24,
    judgment: '亨。出入無疾，朋來無咎。反復其道，七日來復，利有攸往。',
    monograms: [
      { statement: '初九：不遠復，無祇悔，元吉。', meaning: '' },
      { statement: '六二：休復，吉。', meaning: '' },
      { statement: '六三：頻復，厲，無咎。', meaning: '。' },
      { statement: '六四：中行獨復。', meaning: '' },
      { statement: '六五：敦復，無悔。', meaning: '' },
      {
        statement: '上六：迷復，凶，有災眚。用行師，終有大敗。以其國君，凶，至于十年不克征。',
        meaning: '',
      },
    ],
  },
  '100111': {
    name: '無妄',
    index: 25,
    judgment: '元亨利貞。其匪正有眚，不利有攸往。',
    monograms: [
      { statement: '初九：無妄，往吉。', meaning: '' },
      { statement: '六二：不耕穫，不菑畬，則利有攸往。', meaning: '' },
      { statement: '九三：無妄之災，或繫之牛。行人之得，邑人之災。', meaning: '。' },
      { statement: '九四：可貞，無咎。', meaning: '' },
      { statement: '九五：無妄之疾，勿藥有喜。', meaning: '' },
      { statement: '上九：無妄，行有眚，無攸利。', meaning: '' },
    ],
  },
  '111001': {
    name: '大畜',
    index: 26,
    judgment: '利貞，不家食吉，利涉大川。',
    monograms: [
      { statement: '初九：有厲，利已。', meaning: '' },
      { statement: '九二：輿說輹。', meaning: '' },
      { statement: '九三：良馬逐，利艱貞。曰閑輿衛，利有攸往。', meaning: '。' },
      { statement: '六四：童牛之牿，元吉。', meaning: '' },
      { statement: '六五：豶豕之牙，吉。', meaning: '' },
      { statement: '上九：何天之衢，亨。', meaning: '' },
    ],
  },
  '100001': {
    name: '頤',
    index: 27,
    judgment: '貞吉，觀頤，自求口實。',
    monograms: [
      { statement: '初九：舍爾靈龜，觀我朵頤，凶。', meaning: '' },
      { statement: '六二：顛頤，拂經；于丘頤，征凶。', meaning: '' },
      { statement: '六三：拂頤，貞凶。十年勿用，無攸利。', meaning: '。' },
      { statement: '六四：顛頤，吉。虎視眈眈，其欲逐逐，無咎。', meaning: '' },
      { statement: '六五：拂經，居貞吉，不可涉大川。', meaning: '' },
      { statement: '上九：由頤，厲吉，利涉大川。', meaning: '' },
    ],
  },
  '011110': {
    name: '大過',
    index: 28,
    judgment: '棟橈。利有攸往，亨。',
    monograms: [
      { statement: '初六：藉用白茅，無咎。', meaning: '' },
      { statement: '九二：枯楊生稊，老夫得其女妻，無不利。', meaning: '' },
      { statement: '九三：棟橈，凶。', meaning: '。' },
      { statement: '六四：棟隆，吉，有它吝。', meaning: '' },
      { statement: '九五：枯楊生華，老婦得其士夫，無咎無譽。', meaning: '' },
      { statement: '上六：過涉滅頂，凶，無咎。', meaning: '' },
    ],
  },
  '010010': {
    name: '坎',
    index: 29,
    judgment: '習坎，有孚，維心亨，行有尚。',
    monograms: [
      { statement: '初六：習坎，入于坎窞，凶。', meaning: '' },
      { statement: '九二：坎有險，求小得。', meaning: '' },
      { statement: '六三：來之坎坎，險且枕。入于坎窞，勿用。', meaning: '。' },
      { statement: '六四：樽酒，簋貳，用缶。納約自牖，終無咎。', meaning: '' },
      { statement: '九五：坎不盈，祇既平，無咎。', meaning: '' },
      { statement: '上六：係用徽纆，寘于叢棘。三歲不得，凶。', meaning: '' },
    ],
  },
  '101101': {
    name: '離',
    index: 30,
    judgment: '利貞，亨，畜牝牛吉。',
    monograms: [
      { statement: '初九：履錯然，敬之，無咎。', meaning: '' },
      { statement: '六二：黃離，元吉。', meaning: '' },
      { statement: '九三：日昃之離，不鼓缶而歌，則大耊之嗟，凶。', meaning: '。' },
      { statement: '九四：突如其來如，焚如，死如，棄如。', meaning: '' },
      { statement: '六五：出涕沱若，戚嗟若，吉。', meaning: '' },
      { statement: '上九：王用出征，有嘉折首，獲匪其醜，無咎。', meaning: '' },
    ],
  },
  '001110': {
    name: '咸',
    index: 31,
    judgment: '亨利貞，取女吉。',
    monograms: [
      { statement: '初六：咸其拇。', meaning: '' },
      { statement: '六二：咸其腓，凶，居吉。', meaning: '' },
      { statement: '六三：咸其股，執其隨，往吝。', meaning: '。' },
      { statement: '九四：貞吉，悔亡。憧憧往來，朋從爾思。', meaning: '' },
      { statement: '九五：咸其脢，無悔。', meaning: '' },
      { statement: '上六：咸其輔頰舌。', meaning: '' },
    ],
  },
  '011100': {
    name: '恆',
    index: 32,
    judgment: '亨，無咎，利貞，利有攸往。',
    monograms: [
      { statement: '初六：浚恆，貞凶，無攸利。', meaning: '' },
      { statement: '九二：悔亡。', meaning: '' },
      { statement: '九三：不恆其德，或承之羞，貞吝。', meaning: '。' },
      { statement: '九四：田無禽。', meaning: '' },
      { statement: '六五：恆其德貞，婦人吉，夫子凶。', meaning: '' },
      { statement: '上六：振恆，凶。', meaning: '' },
    ],
  },
  '001111': {
    name: '遯',
    index: 33,
    judgment: '亨，小利貞。',
    monograms: [
      { statement: '初六：遯尾厲，勿用有攸往。', meaning: '' },
      { statement: '六二：執之用黃牛之革，莫之勝說。', meaning: '' },
      { statement: '九三：係遯，有疾厲，畜臣妾吉。', meaning: '。' },
      { statement: '九四：好遯，君子吉，小人否。', meaning: '' },
      { statement: '九五：嘉遯，貞吉。', meaning: '' },
      { statement: '上九：肥遯，無不利。', meaning: '' },
    ],
  },
  '111100': {
    name: '大壯',
    index: 34,
    judgment: '利貞。',
    monograms: [
      { statement: '初九：壯于趾，征凶，有孚。', meaning: '' },
      { statement: '九二：貞吉。', meaning: '' },
      { statement: '九三：小人用壯，君子用罔，貞厲。羝羊觸藩，羸其角。', meaning: '。' },
      { statement: '九四：貞吉，悔亡。藩決不羸，壯于大輿之輹。', meaning: '' },
      { statement: '六五：喪羊于易，無悔。', meaning: '' },
      { statement: '上六：羝羊觸藩，不能退，不能遂。無攸利，艱則吉。', meaning: '' },
    ],
  },
  '000101': {
    name: '晉',
    index: 35,
    judgment: '康侯用錫馬蕃庶，晝日三接。',
    monograms: [
      { statement: '初六：晉如摧如，貞吉。罔孚，裕無咎。', meaning: '' },
      { statement: '六二：晉如愁如，貞吉。受茲介福，于其王母。', meaning: '' },
      { statement: '六三：眾允，悔亡。', meaning: '。' },
      { statement: '九四：晉如鼫鼠，貞厲。', meaning: '' },
      { statement: '六五：悔亡，失得勿恤。往吉，無不利。', meaning: '' },
      { statement: '上九：晉其角，維用伐邑。厲吉無咎，貞吝。', meaning: '' },
    ],
  },
  '101000': {
    name: '明夷',
    index: 36,
    judgment: '利艱貞。',
    monograms: [
      { statement: '初九：明夷于飛，垂其翼，君子于行，三日不食。有攸往，主人有言。', meaning: '' },
      { statement: '六二：明夷，夷于左股，用拯馬壯吉。', meaning: '' },
      { statement: '九三：明夷于南狩，得其大首，不可疾貞。', meaning: '。' },
      { statement: '六四：入于左腹，獲明夷之心，于出門庭。', meaning: '' },
      { statement: '六五：箕子之明夷，利貞。', meaning: '' },
      { statement: '上六：不明晦，初登于天，後入于地。', meaning: '' },
    ],
  },
  '101011': {
    name: '家人',
    index: 37,
    judgment: '利女貞。',
    monograms: [
      { statement: '初九：閑有家，悔亡。', meaning: '' },
      { statement: '六二：無攸遂，在中饋，貞吉。', meaning: '' },
      { statement: '九三：家人嗃嗃，悔厲吉。婦子嘻嘻，終吝。', meaning: '。' },
      { statement: '六四：富家，大吉。', meaning: '' },
      { statement: '九五：王假有家，勿恤，吉。', meaning: '' },
      { statement: '上九：有孚威如，終吉。', meaning: '' },
    ],
  },
  '110101': {
    name: '睽',
    index: 38,
    judgment: '小事吉。',
    monograms: [
      { statement: '初九：悔亡，喪馬勿逐自復。見惡人，無咎。', meaning: '' },
      { statement: '九二：遇主于巷，無咎。', meaning: '' },
      { statement: '六三：見輿曳，其牛掣。其人天且劓，無初有終。', meaning: '。' },
      { statement: '九四：睽孤，遇元夫。交孚，厲，無咎。', meaning: '' },
      { statement: '六五：悔亡。厥宗噬膚，往何咎？', meaning: '' },
      {
        statement: '上九：睽孤，見豕負塗，載鬼一車。先張之弧，後說之弧。匪寇婚媾。往，遇雨則吉。',
        meaning: '',
      },
    ],
  },
  '001010': {
    name: '蹇',
    index: 39,
    judgment: '利西南，不利東北。利見大人，貞吉。',
    monograms: [
      { statement: '初六：往蹇來譽。', meaning: '' },
      { statement: '六二：王臣蹇蹇，匪躬之故。', meaning: '' },
      { statement: '九三：往蹇來反。', meaning: '。' },
      { statement: '六四：往蹇來連。', meaning: '' },
      { statement: '九五：大蹇朋來。', meaning: '' },
      { statement: '上六：往蹇來碩，吉，利見大人。', meaning: '' },
    ],
  },
  '010100': {
    name: '解',
    index: 40,
    judgment: '利西南。無所往，其來復吉；有攸往，夙吉。',
    monograms: [
      { statement: '初六：無咎。', meaning: '' },
      { statement: '九二：田獲三狐，得黃矢，貞吉。', meaning: '' },
      { statement: '六三：負且乘，致寇至，貞吝。', meaning: '。' },
      { statement: '九四：解而拇，朋至斯孚。', meaning: '' },
      { statement: '六五：君子維有解，吉，有孚于小人。', meaning: '' },
      { statement: '上六：公用射隼于高墉之上，獲之，無不利。', meaning: '' },
    ],
  },
  '110001': {
    name: '損',
    index: 41,
    judgment: '有孚，元吉，無咎，可貞，利有攸往。曷之用？二簋可用享。',
    monograms: [
      { statement: '初九：已事遄往，無咎。酌損之。', meaning: '' },
      { statement: '九二：利貞，征凶。弗損，益之。', meaning: '' },
      { statement: '六三：三人行，則損一人；一人行，則得其友。', meaning: '。' },
      { statement: '六四：損其疾，使遄有喜。無咎。', meaning: '' },
      { statement: '六五：或益之十朋之龜，弗克違，元吉。', meaning: '' },
      { statement: '上九：弗損，益之。無咎，貞吉，利有攸往。得臣無家。', meaning: '' },
    ],
  },
  '100011': {
    name: '益',
    index: 42,
    judgment: '利有攸往，利涉大川。',
    monograms: [
      { statement: '初九：利用為大作，元吉，無咎。', meaning: '' },
      { statement: '六二：或益之十朋之龜，弗克違，永貞吉。王用享于帝，吉。', meaning: '' },
      { statement: '六三：益之用凶事，無咎。有孚中行，告公用圭。', meaning: '。' },
      { statement: '六四：中行，告公從，利用為依遷國。', meaning: '' },
      { statement: '九五：有孚惠心，勿問，元吉。有孚惠我德。', meaning: '' },
      { statement: '上九：莫益之，或擊之。立心勿恆，凶。', meaning: '' },
    ],
  },
  '111110': {
    name: '夬',
    index: 43,
    judgment: '揚于王庭，孚號有厲。告自邑，不利即戎，利有攸往。',
    monograms: [
      { statement: '初九：壯于前趾，往不勝為咎。', meaning: '' },
      { statement: '九二：惕號，莫夜有戎，勿恤。', meaning: '' },
      { statement: '九三：壯于頄，有凶。君子夬夬，獨行遇雨，若濡有慍，無咎。', meaning: '。' },
      { statement: '九四：臀無膚，其行次且。牽羊悔亡，聞言不信。', meaning: '' },
      { statement: '九五：莧陸夬夬，中行無咎。', meaning: '' },
      { statement: '上六：無號，終有凶。', meaning: '' },
    ],
  },
  '011111': {
    name: '姤',
    index: 44,
    judgment: '女壯，勿用取女。',
    monograms: [
      { statement: '初六：繫于金柅，貞吉。有攸往，見凶。羸豕孚蹢躅。', meaning: '' },
      { statement: '九二：包有魚，無咎，不利賓。', meaning: '' },
      { statement: '九三：臀無膚，其行次且。厲，無大咎。', meaning: '。' },
      { statement: '九四：包無魚，起凶。', meaning: '' },
      { statement: '九五：以杞包瓜，含章，有隕自天。', meaning: '' },
      { statement: '上九：姤其角，吝，無咎。', meaning: '' },
    ],
  },
  '000110': {
    name: '萃',
    index: 45,
    judgment: '亨。王假有廟，利見大人。亨利貞，用大牲吉，利有攸往。',
    monograms: [
      { statement: '初六：有孚不終，乃亂乃萃。若號，一握為笑，勿恤，往無咎。', meaning: '' },
      { statement: '六二：引吉無咎，孚乃利用禴。', meaning: '' },
      { statement: '六三：萃如嗟如，無攸利。往無咎，小吝。', meaning: '。' },
      { statement: '九四：大吉無咎。', meaning: '' },
      { statement: '九五：萃有位，無咎。匪孚，元永貞，悔亡。', meaning: '' },
      { statement: '上六：齎咨涕洟，無咎。', meaning: '' },
    ],
  },
  '011000': {
    name: '升',
    index: 46,
    judgment: '元亨。用見大人，勿恤，南征吉。',
    monograms: [
      { statement: '初六：允升，大吉。', meaning: '' },
      { statement: '九二：孚乃利用禴，無咎。', meaning: '' },
      { statement: '九三：升虛邑。', meaning: '。' },
      { statement: '六四：王用亨于岐山，吉，無咎。', meaning: '' },
      { statement: '六五：貞吉，升階。', meaning: '' },
      { statement: '上六：冥升，利于不息之貞。', meaning: '' },
    ],
  },
  '010110': {
    name: '困',
    index: 47,
    judgment: '亨，貞大人吉，無咎。有言不信。',
    monograms: [
      { statement: '初六：臀困于株木，入于幽谷，三歲不覿。', meaning: '' },
      { statement: '九二：困于酒食，朱紱方來，利用享祀，征凶，無咎。', meaning: '' },
      { statement: '六三：困于石，據于蒺蔾，入于其宮，不見其妻，凶。', meaning: '。' },
      { statement: '九四：來徐徐，困于金車。吝，有終。', meaning: '' },
      { statement: '九五：劓刖，困于赤紱。乃徐有說，利用祭祀。', meaning: '' },
      { statement: '上六：困于葛藟，于臲卼，曰動悔有悔，征吉。', meaning: '' },
    ],
  },
  '011010': {
    name: '井',
    index: 48,
    judgment: '改邑不改井，無喪無得，往來井井。汔至，亦未繘井，羸其瓶，凶。',
    monograms: [
      { statement: '初六：井泥不食，舊井無禽。', meaning: '' },
      { statement: '九二：井谷射鮒，甕敝漏。', meaning: '' },
      { statement: '六三：井渫不食，為我心惻。可用汲，王明並受其福。', meaning: '。' },
      { statement: '六四：井甃無咎。', meaning: '' },
      { statement: '九五：井洌，寒泉食。', meaning: '' },
      { statement: '上六：井收勿幕，有孚元吉。', meaning: '' },
    ],
  },
  '101110': {
    name: '革',
    index: 49,
    judgment: '已日乃孚，元亨利貞，悔亡。',
    monograms: [
      { statement: '初九：鞏用黃牛之革。', meaning: '' },
      { statement: '六二：已日乃革之，征吉，無咎。', meaning: '' },
      { statement: '九三：征凶，貞厲。革言三就，有孚。', meaning: '。' },
      { statement: '九四：悔亡，有孚改命吉。', meaning: '' },
      { statement: '九五：大人虎變，未占有孚。', meaning: '' },
      { statement: '上六：君子豹變，小人革面。征凶，居貞吉。', meaning: '' },
    ],
  },
  '011101': {
    name: '鼎',
    index: 50,
    judgment: '元吉亨。',
    monograms: [
      { statement: '初六：鼎顚趾，利出否，得妾以其子，無咎。', meaning: '' },
      { statement: '九二：鼎有實，我仇有疾，不我能即，吉。', meaning: '' },
      { statement: '九三：鼎耳革，其行塞，雉膏不食。方雨虧悔，終吉。', meaning: '。' },
      { statement: '九四：鼎折足，覆公餗，其形渥，凶。', meaning: '' },
      { statement: '六五：鼎黃耳金鉉，利貞。', meaning: '' },
      { statement: '上九：鼎玉鉉，大吉，無不利。', meaning: '' },
    ],
  },
  '100100': {
    name: '震',
    index: 51,
    judgment: '亨，震來虩虩，笑言啞啞。震驚百里，不喪匕鬯。',
    monograms: [
      { statement: '初九：震來虩虩，後笑言啞啞，吉。', meaning: '' },
      { statement: '六二：震來厲，億喪貝，躋于九陵。勿逐，七日得。', meaning: '' },
      { statement: '六三：震蘇蘇，震行無眚。', meaning: '。' },
      { statement: '九四：震遂泥。', meaning: '' },
      { statement: '六五：震往來厲，億無喪有事。', meaning: '' },
      {
        statement: '上六：震索索，視矍矍，征凶。震不于其躬，于其鄰，無咎。婚媾有言。',
        meaning: '',
      },
    ],
  },
  '001001': {
    name: '艮',
    index: 52,
    judgment: '艮其背，不獲其身。行其庭，不見其人，無咎。',
    monograms: [
      { statement: '初六：艮其趾，無咎，利永貞。', meaning: '' },
      { statement: '六二：艮其腓，不拯其隨，其心不快。', meaning: '' },
      { statement: '九三：艮其限，列其夤，厲薰心。', meaning: '。' },
      { statement: '六四：艮其身，無咎。', meaning: '' },
      { statement: '六五：艮其輔，言有序，悔亡。', meaning: '' },
      { statement: '上九：敦艮吉。', meaning: '' },
    ],
  },
  '001011': {
    name: '漸',
    index: 53,
    judgment: '女歸吉，利貞。',
    monograms: [
      { statement: '初六：鴻漸于干，小子厲，有言，無咎。', meaning: '' },
      { statement: '六二：鴻漸于磐，飲食衎衎，吉。', meaning: '' },
      { statement: '九三：鴻漸于陸，夫征不復，婦孕不育，凶。利禦寇。', meaning: '。' },
      { statement: '六四：鴻漸于木，或得其桷，無咎。', meaning: '' },
      { statement: '九五：鴻漸于陵，婦三歲不孕。終莫之勝，吉。', meaning: '' },
      { statement: '上九：鴻漸于陸，其羽可用為儀，吉。', meaning: '' },
    ],
  },
  '110100': {
    name: '歸妹',
    index: 54,
    judgment: '征凶，無攸利。',
    monograms: [
      { statement: '初九：歸妹以娣，跛能履，征吉。', meaning: '' },
      { statement: '九二：眇能視 ，利幽人之貞。', meaning: '' },
      { statement: '六三：歸妹以須，反歸以娣。', meaning: '。' },
      { statement: '九四：歸妹愆期，遲歸有時。', meaning: '' },
      { statement: '六五：帝乙歸妹，其君之袂不如其娣之袂良。月幾望，吉。', meaning: '' },
      { statement: '上六：女承筐無實，士刲羊無血，無攸利。', meaning: '' },
    ],
  },
  '101100': {
    name: '豐',
    index: 55,
    judgment: '亨，王假之。勿憂，宜日中。',
    monograms: [
      { statement: '初九：遇其配主，雖旬無咎，往有尚。', meaning: '' },
      { statement: '六二：豐其蔀，日中見斗。往得疑疾，有孚發若，吉。', meaning: '' },
      { statement: '九三：豐其沛，日中見沬 。折其右肱，無咎。', meaning: '。' },
      { statement: '九四：豐其蔀，日中見斗，遇其夷主，吉。', meaning: '' },
      { statement: '六五：來章，有慶譽，吉。', meaning: '' },
      { statement: '上六：豐其屋，蔀其家。闚其戶，闃其無人 ，三歲不覿，凶。', meaning: '' },
    ],
  },
  '001101': {
    name: '旅',
    index: 56,
    judgment: '小亨，旅貞吉。',
    monograms: [
      { statement: '初六：旅瑣瑣，斯其所取災。', meaning: '' },
      { statement: '六二：旅即次，懷其資，得童僕貞。', meaning: '' },
      { statement: '九三：旅焚其次，喪其童僕，貞厲。', meaning: '。' },
      { statement: '九四：旅于處，得其資斧，我心不快。', meaning: '' },
      { statement: '六五：射雉，一矢亡，終以譽命。', meaning: '' },
      { statement: '上九：鳥焚其巢，旅人先笑後號咷。喪牛于易，凶。', meaning: '' },
    ],
  },
  '011011': {
    name: '巽',
    index: 57,
    judgment: '小亨，利有攸往，利見大人。',
    monograms: [
      { statement: '初六：進退，利武人之貞。', meaning: '' },
      { statement: '九二：巽在牀下，用史巫紛若，吉，無咎。', meaning: '' },
      { statement: '九三：頻巽，吝。', meaning: '。' },
      { statement: '六四：悔亡，田獲三品。', meaning: '' },
      { statement: '九五：貞吉，悔亡，無不利。無初有終，先庚三日，後庚三日，吉。', meaning: '' },
      { statement: '上九：巽在牀下，喪其資斧，貞凶。', meaning: '' },
    ],
  },
  '110110': {
    name: '兌',
    index: 58,
    judgment: '亨利貞。',
    monograms: [
      { statement: '初九：和兌吉。', meaning: '' },
      { statement: '九二：孚兌吉，悔亡。', meaning: '' },
      { statement: '六三：來兌凶。', meaning: '。' },
      { statement: '九四：商兌未寧，介疾有喜。', meaning: '' },
      { statement: '九五：孚于剝，有厲。', meaning: '' },
      { statement: '上六：引兌。', meaning: '' },
    ],
  },
  '010011': {
    name: '渙',
    index: 59,
    judgment: '亨。王假有廟，利涉大川，利貞。',
    monograms: [
      { statement: '初六：用拯馬壯，吉。', meaning: '' },
      { statement: '九二：渙奔其机，悔亡。', meaning: '' },
      { statement: '六三：渙其躬，無悔。', meaning: '。' },
      { statement: '六四：渙其群，元吉。渙有丘，匪夷所思。', meaning: '' },
      { statement: '九五：渙汗其大號，渙王居，無咎。', meaning: '' },
      { statement: '上九：渙其血去逖出，無咎。', meaning: '' },
    ],
  },
  '110010': {
    name: '節',
    index: 60,
    judgment: '亨。苦節不可貞。',
    monograms: [
      { statement: '初九：不出戶庭，無咎。', meaning: '' },
      { statement: '九二：不出門庭，凶。', meaning: '' },
      { statement: '六三：不節若，則嗟若，無咎。', meaning: '。' },
      { statement: '六四：安節，亨。', meaning: '' },
      { statement: '九五：甘節，吉，往有尚。', meaning: '' },
      { statement: '上六：苦節，貞凶，悔亡。', meaning: '' },
    ],
  },
  '110011': {
    name: '中孚',
    index: 61,
    judgment: '豚魚吉。利涉大川，利貞。',
    monograms: [
      { statement: '初九：虞吉，有它不燕。', meaning: '' },
      { statement: '九二：鳴鶴在陰，其子和之。我有好爵，吾與爾靡之。', meaning: '' },
      { statement: '六三：得敵，或鼓或罷，或泣或歌。', meaning: '。' },
      { statement: '六四：月幾望，馬匹亡，無咎。', meaning: '' },
      { statement: '九五：有孚攣如，無咎。', meaning: '' },
      { statement: '上九：翰音登于天，貞凶。', meaning: '' },
    ],
  },
  '001100': {
    name: '小過',
    index: 62,
    judgment: '亨，利貞。可小事，不可大事。飛鳥遺之音，不宜上，宜下，大吉。',
    monograms: [
      { statement: '初六：飛鳥以凶。', meaning: '' },
      { statement: '六二：過其祖，遇其妣。不及其君，遇其臣，無咎。', meaning: '' },
      { statement: '九三：弗過防之，從或戕之，凶。', meaning: '。' },
      { statement: '九四：無咎，弗過遇之，往厲必戒，勿用永貞。', meaning: '' },
      { statement: '六五：密雲不雨，自我西郊，公弋取彼在穴。', meaning: '' },
      { statement: '上六：弗遇過之，飛鳥離之，凶，是謂災眚。', meaning: '' },
    ],
  },
  '101010': {
    name: '既濟',
    index: 63,
    judgment: '亨小，利貞，初吉終亂。',
    monograms: [
      { statement: '初九：曳其輪，濡其尾，無咎。', meaning: '' },
      { statement: '六二：婦喪其茀，勿逐，七日得。', meaning: '' },
      { statement: '九三：高宗伐鬼方，三年克之。小人勿用。', meaning: '。' },
      { statement: '六四：繻有衣袽，終日戒。', meaning: '' },
      { statement: '九五：東鄰殺牛，不如西鄰之禴祭，實受其福。', meaning: '' },
      { statement: '上六：濡其首，厲。', meaning: '' },
    ],
  },
  '010101': {
    name: '既濟',
    index: 64,
    judgment: '亨。小狐汔濟，濡其尾，無攸利。',
    monograms: [
      { statement: '初六：濡其尾，吝。', meaning: '' },
      { statement: '九二：曳其輪，貞吉。', meaning: '' },
      { statement: '六三：未濟，征凶，利涉大川。', meaning: '。' },
      { statement: '九四：貞吉悔亡，震用伐鬼方，三年有賞于大國。', meaning: '' },
      { statement: '六五：貞吉無悔，君子之光，有孚，吉。', meaning: '' },
      { statement: '上九：有孚于飲酒，無咎。濡其首，有孚失是。', meaning: '' },
    ],
  },
};
